version: '2'
services:
  zazzn:
    build: .
    container_name: teleport
    restart: unless-stopped
    ports:
      - 3022:3022/tcp
      - 3023:3023/tcp
      - 3024:3024/tcp
      - 3025:3025/tcp
      - 3080:3080/tcp
    environment:
      - TZ=America/Dawson
    hostname: teleport
    volumes:
      - /home/teleport:/var/lib/teleport
#    commnad: tctl users add teleport

